Change dataflow and nificluster controllers to avoid changing status on every reconciliation loop
konpyutaika/nifikop pull request #142
Opened 2022-08-23 12:30 UTC by michael81877

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #119 
| License         | Apache 2.0

### What's in this PR?

Tweaks `NifiCluster` and `NifiDataflow` controllers to avoid changing their respective statuses on every reconciliation loop. Instead, the controllers will only change the status to ready/done and log any actions taken thereafter and they will respect their reconciliation interval settings (15s by default). Previously to this, the controllers would reconcile many times _per second_, which drastically increases the load on the control plane and on NiFi itself.

Additionally, i changed the logger timestamp encoder to user ISO8601 instead of epoch time so it is human readable.

### Why?

Issue #119 does an excellent job of explaining why this is an issue.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)
- [x] Append changelog with changes

2022-08-23 12:41 UTC, michael81877 commented on controllers/nificluster_controller.go
> +	return RequeueAfter(intervalRunning)
@cannonpalms asked:

> Can you speak to the strategy for watching child resources (namely pods) now that the NifiCluster controller is not flapping?

Prior to this change, the `NifiCluster` controller perpetually scheduled reconciliation requests by updating its own status (`Reconciling` vs `Running`). The controller still watches all of the resources it was watching before. The difference is that now the controller schedules reconciliation requests respecting its reconciliation interval of `15s` -- that's the change on this line of code. Reconciliation requests will also be triggered if the `NifiCluster` CRD is modified by a user.

The same is true for the `NifiDataflow` controller.

2022-08-23 19:12 UTC, erdrix requested changes
It would be nice to replace the deleted state change with an event notification to keep the information, but in a better place ?

2022-08-24 08:34 UTC, michael81877 commented
> It would be nice to replace the deleted state change with an event notification to keep the information, but in a better place ?

Definitely! Let me add an event there instead

2022-08-24 09:44 UTC, michael81877 commented
@erdrix I've made sure an event notification and log message are generated when the controllers begin & end reconciliation 👍

2022-08-24 13:58 UTC, r65535 commented
LGTM!
@erdrix - was there a reason for adding `RequeueAfter(interval / 3)` to the dataflow controller [here](https://github.com/konpyutaika/nifikop/blame/49a9b5e1ac8d596bb388a43bdedeb0135923c7d3/controllers/nifidataflow_controller.go#L471)?

2022-08-24 20:27 UTC, erdrix commented
> LGTM! @erdrix - was there a reason for adding `RequeueAfter(interval / 3)` to the dataflow controller [here](https://github.com/konpyutaika/nifikop/blame/49a9b5e1ac8d596bb388a43bdedeb0135923c7d3/controllers/nifidataflow_controller.go#L471)?

If so, I can't remember why...

2022-08-24 20:27 UTC, erdrix approved these changes

2022-08-24 20:29 UTC, erdrix commented
@cannonpalms, can you confirm that this solves some of your problems?

2022-08-25 07:26 UTC, michael81877 commented
> > LGTM! @erdrix - was there a reason for adding `RequeueAfter(interval / 3)` to the dataflow controller [here](https://github.com/konpyutaika/nifikop/blame/49a9b5e1ac8d596bb388a43bdedeb0135923c7d3/controllers/nifidataflow_controller.go#L471)?
> 
> If so, I can't remember why...

Since the dataflow controller will now respect its interval, should we either revert the division or reset the default interval the 5? (`15 / 3`)?

2022-08-25 10:45 UTC, michael81877 commented
Just FYI i've deployed this branch w/ argo to a remote k8s cluster and verified that the `NifiCluster` and `NifiDataflow` resource are no longer constantly upgrading

<img width="296" alt="image" src="https://user-images.githubusercontent.com/86672176/186644747-db44b754-37eb-4ee7-ada0-e4d7a921a200.png">

A screenshot doesn't really prove this, but the resource `resourceVersion` fields are not updating unless I change the CRDs.

2022-08-25 11:24 UTC, erdrix approved these changes

2022-08-25 11:24 UTC, merged