Update 2_istio_service_mesh.md
konpyutaika/nifikop pull request #228
Opened 2023-01-26 12:31 UTC by ggerla

| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?

### Why?

### Additional context

### Checklist

- [ ] Implementation tested
- [ ] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [ ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)
- [ ] Append changelog with changes

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2023-02-28 09:44 UTC, mh013370 approved these changes
This LGTM. 

@juldrixx , @erdrix : Any feedback?

2023-02-28 10:23 UTC, juldrixx requested changes

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +The following example show ho to define a gateway that will be able to intercept all requests for a specific domain host on http port 80.
show ho ->  show how

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +The purpose of this section is to explain how expose your NiFi cluster using Istio on kubernetes.
kubernetes -> Kubernetes

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +The purpose of this section is to explain how expose your NiFi cluster using Istio on kubernetes.
how expose -> how to expose

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +To access to the NiFi cluster from the external world, it is needed to configure a gateway and a virtual service on Istio.
gateway -> `Gateway`
virtual service -> `VirtualService`

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +The following example show ho to define a gateway that will be able to intercept all requests for a specific domain host on http port 80.
gateway -> `Gateway`
http -> HTTP

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +In combination, we need to define also a virtual service that redirect all requests itercepted by the gateway to a specific service.
gateway -> `Gateway`
virtual service -> `VirtualService`

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +In case you are deploying a cluster and you want enable the HTTPS protocol to manage user authentication, the configuration is more complex. To understand the reason of this, it is important to expla
you want enable -> you want to enable

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +To solve this issue, the tricky is so limit the HTTPS session till the gateway, then decrypt all requests in HTTP, manage the sticky session and then encrypt again in HTTPS before reach the NiFi node
the tricky is so limit ->  the trick is to limit

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +Istio allows to do this using a destination rule combined with the virtual service. In the next example we define a gateway that accepts HTTPS traffic and transform it in HTTP.
gateway -> `Gateway`
virtual service -> `VirtualService`
In the next example we define -> In the next example, we define

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +In combination, we need to define also a virtual service that redirect all HTTP traffic to a specific the cluster service.
virtual service -> `VirtualService`
to a specific the cluster service -> to a specific cluster `Service` (not sure what was supposed to be said)

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +Please note that the service name configured as destination of the virtual service is the name of the service created with the following section in the cluster deployment yaml
virtual service -> `VirtualService`
the name of the service -> `Service`
deployment -> `Deployment`
yaml -> YAML

2023-02-28 10:23 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +Finally the destination rule that redirect all HTTP traffic destinated to the cluster service to HTTPS encrypting it.
service -> `Service`

2023-02-28 10:26 UTC, juldrixx commented
> This LGTM.
> 
> @juldrixx , @erdrix : Any feedback?

I can't evaluate the substance of the PR but I can evaluate the form 😊, may be @erdrix can on the substance.

2023-02-28 10:27 UTC, erdrix commented
> This LGTM.
> 
> @juldrixx , @erdrix : Any feedback?

Maybe wrong memories, but I thought some configuration was needed in nifi.properties (`nifi.web.http.network.interface.default=eth0` `nifi.web.http.network.interface.lo=lo`) [to work with Istio](https://github.com/istio/istio/issues/17918#issuecomment-664377996)? Did it work without it?

2023-03-01 16:06 UTC, ggerla commented
@juldrixx I fixed all your comment... for "cluster service" I used ClusterIP Service

@erdrix yes I read the same... but the configuration I posted was tested in my env and it works. Maybe the operator already set properly the nifi.properties? Honestly I don't remember and I'm not able to check it right now

2023-03-01 18:13 UTC, juldrixx requested changes

2023-03-01 18:13 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +In combination, we need to define also a VirtualService that redirect all requests itercepted by the Gateway to a specific service.
In fact,  I was suggesting to put \`VirtualService\` and \`Gateway\` to have a nice formatting

2023-03-01 18:13 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +The following example show how to define a Gateway that will be able to intercept all requests for a specific domain host on HTTP port 80.
In fact,  I was suggesting to put \`Gateway\` to have a nice formatting

2023-03-01 18:13 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +To solve this issue, the tricky is to limit the HTTPS session till the Gateway, then decrypt all requests in HTTP, manage the sticky session and then encrypt again in HTTPS before reach the NiFi node
In fact,  I was suggesting to put \`Gateway\` to have a nice formatting

2023-03-01 18:13 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +Istio allows to do this using a destination rule combined with the VirtualService. In the next example, we define a Gateway that accepts HTTPS traffic and transform it in HTTP.
In fact,  I was suggesting to put \`VirtualService\` and \`Gateway\` to have a nice formatting

2023-03-01 18:13 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +In combination, we need to define also a VirtualService that redirect all HTTP traffic to a specific the ClusterIP Service.
In fact,  I was suggesting to put \`VirtualService\` and \`ClusterIP\` to have a nice formatting

2023-03-01 18:13 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +Please note that the service name configured as destination of the VirtualService is the name of the Service created with the following section in the cluster Deployment YAML
In fact,  I was suggesting to put \`VirtualService\` , \`Deployment\` and \`ClusterIP\` to have a nice formatting

2023-03-01 18:13 UTC, juldrixx commented on site/website/versioned_docs/version-v1.0.0/3_manage_nifi/1_manage_clusters/1_deploy_cluster/3_expose_cluster/2_istio_service_mesh.md
> +Finally the destination rule that redirect all HTTP traffic destinated to the ClusterIP Service to HTTPS encrypting it.
In fact,  I was suggesting to put \`ClusterIP\` to have a nice formatting

2023-03-14 08:22 UTC, juldrixx approved these changes

2023-03-14 08:22 UTC, merged