Migrate kubebuilder v4
konpyutaika/nifikop pull request #366
Opened 2024-01-16 15:47 UTC by mh013370

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #365 
| License         | Apache 2.0

### What's in this PR?

Migrates the operator to KubeBuilder go/v4 and operator-sdk v1.33.0, applying all appropriate migrations in the process. The migration process required re-scaffolding the entire API and all controllers in order to regenerate the `PROJECT` configuration, but the actual specs & controller code was copied forward. Regardless, care should be taken in reviewing this to ensure that i did not incidentally leave something out.

I updated the `Makefile` and all generated Kustomize configuration to match the latest in KubeBuilder. From this point, only minor updates should be required.

### Why?

KubeBuilder go/v4 is now stable and go/v3 will be end-of-lifed and removed.

### Checklist

- [ ] Implementation tested
- [x] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)
- [ ] Append changelog with changes

2024-01-16 15:59 UTC, juldrixx requested changes
Before taking an in-depth look and testing it, I think that the version of Operator SDK is mentionned in the documention (not sure for Kubebuilder itself), so it must be updated accordingly.

2024-01-16 16:01 UTC, mh013370 commented
> Before taking an in-depth look and testing it, I think that the version of Operator SDK is mentionned in the documention (not sure for Kubebuilder itself), so it must be updated accordingly.

Yeah, so basically upgrading to operador-sdk v1.33.0 is just migrating to kubebuilder go/v4: 

https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.33.0/

2024-01-16 16:01 UTC, r65535 reviewed
Initial checks LGTM.
I'll test a few cluster deployments using this branch tomorrow 👍

2024-01-16 16:03 UTC, juldrixx commented
> > Before taking an in-depth look and testing it, I think that the version of Operator SDK is mentionned in the documention (not sure for Kubebuilder itself), so it must be updated accordingly.
> 
> Yeah, so basically upgrading to operador-sdk v1.33.0 is just migrating to kubebuilder go/v4:
> 
> https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.33.0/

I was thinking of NiFiKop documentation 😄

2024-01-16 16:06 UTC, mh013370 commented
> ng of NiFiKop document



> > > Before taking an in-depth look and testing it, I think that the version of Operator SDK is mentionned in the documention (not sure for Kubebuilder itself), so it must be updated accordingly.
> > 
> > 
> > Yeah, so basically upgrading to operador-sdk v1.33.0 is just migrating to kubebuilder go/v4:
> > https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.33.0/
> 
> I was thinking of NiFiKop documentation 😄

You're right it is. Updated :)

2024-01-16 16:06 UTC, mh013370 commented on go.mod
> +go 1.21.5
KubeBuilder actually added the minor version, but i like that it's explicit so when `govuln` finds an issue prompting an update we can just go in an up the minor version.

Thoughts?

2024-01-16 16:11 UTC, r65535 commented on go.mod
> +go 1.21.5
Yeah I agree - it requires more maintenance from committers but think it's worth the price.
It's also explicit for users, so they can see which version we're using for each release.

2024-02-09 15:45 UTC, juldrixx requested changes

2024-02-09 15:45 UTC, juldrixx commented on go.mod
> +go 1.21.5
```suggestion
go 1.21.7
```

2024-02-09 15:46 UTC, juldrixx approved these changes

2024-02-09 15:52 UTC, merged