add ldaps settings
konpyutaika/nifikop pull request #391
Opened 2024-02-15 20:37 UTC by wrender

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?
Adding settings required to do secure LDAP with nifi

### Why?
Missing settings for doing secure LDAP

### Checklist

- [ ] Implementation tested
- [ ] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [ ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)
- [ ] Append changelog with changes

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2024-02-16 08:42 UTC, mh013370 commented on pkg/resources/templates/config/login_identity_providers.go
> +        <property name="Referral Strategy">{{or .LdapConfiguration.ReferralStrategy "FOLLOW"}}</property>
```suggestion
        <property name="Referral Strategy">{{or .LdapConfiguration.ReferralStrategy "FOLLOW"}}</property>
```

2024-02-16 08:47 UTC, mh013370 commented
Would you mind updating the LDAP documentation here for the new configurable fields?

https://github.com/konpyutaika/nifikop/blob/master/site/docs/5_references/1_nifi_cluster/1_nifi_cluster.md?plain=1#L189-L196

2024-02-16 22:11 UTC, wrender commented on api/v1/nificluster_types.go
> +	TLSKeystore string `json:"tlsKeystore,omitempty"`
Ok. Done

2024-02-16 22:11 UTC, wrender commented
> Would you mind updating the LDAP documentation here for the new configurable fields?
> 
> https://github.com/konpyutaika/nifikop/blob/master/site/docs/5_references/1_nifi_cluster/1_nifi_cluster.md?plain=1#L189-L196

Ok. Done

2024-02-26 13:15 UTC, juldrixx requested changes

2024-02-26 13:15 UTC, juldrixx commented on api/v1/nificluster_types.go
> +	TLSKeystore string `json:"tlsKeystore,omitempty"`
```suggestion
	// Path to the Keystore that is used when connecting to LDAP using LDAPS or START_TLS.
	// The TLS Keystore settings are optional and only used if your LDAP/AD server needs mutual TLS.
	TLSKeystore string `json:"tlsKeystore,omitempty"`
```

2024-03-04 22:47 UTC, wrender commented
For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container.  Am I missing something?  For example:
```
ldapConfiguration
  enabled: true
  tlsTruststore:  /some/path
```
Then if I exec into the container, and cat conf/login-identity-providers.xml  , The value for that line item is empty.

2024-03-05 09:51 UTC, mh013370 commented on site/docs/5_references/1_nifi_cluster/1_nifi_cluster.md
> +| referralStrategy        | string | Strategy for handling referrals. Possible values are FOLLOW, IGNORE, THROW.                                                                | No       | ""
```suggestion
| referralStrategy        | string | Strategy for handling referrals. Possible values are FOLLOW, IGNORE, THROW.                                                                | No       | FOLLOW          |
```

2024-03-05 09:53 UTC, mh013370 commented
Just one minor doc suggestion. otherwise it looks good to me

2024-03-05 13:29 UTC, wrender commented
> > For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container. Am I missing something? For example:
> > ```
> > ldapConfiguration
> >   enabled: true
> >   tlsTruststore:  /some/path
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then if I exec into the container, and cat conf/login-identity-providers.xml , The value for that line item is empty.
> 
> Just double checking you've applied the new CRDs here and the updated operator?

I deleted the CRDs and re-created them with the helm chart. Maybe I'm not updating the operator correctly? How would I update that?

2024-03-05 13:34 UTC, mh013370 commented
> > > For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container. Am I missing something? For example:
> > > ```
> > > ldapConfiguration
> > >   enabled: true
> > >   tlsTruststore:  /some/path
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then if I exec into the container, and cat conf/login-identity-providers.xml , The value for that line item is empty.
> > 
> > 
> > Just double checking you've applied the new CRDs here and the updated operator?
> 
> I deleted the CRDs and re-created them with the helm chart. Maybe I'm not updating the operator correctly? How would I update that?

There's a thread in slack where folks talk about that: https://konpytika.slack.com/archives/C0362VBRM24/p1702911625342399

TLDR is that the helm client doesn't do it for you, but tools like ArgoCD/Flux will do it for you. 

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

2024-03-05 13:52 UTC, wrender commented
> > > > For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container. Am I missing something? For example:
> > > > ```
> > > > ldapConfiguration
> > > >   enabled: true
> > > >   tlsTruststore:  /some/path
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Then if I exec into the container, and cat conf/login-identity-providers.xml , The value for that line item is empty.
> > > 
> > > 
> > > Just double checking you've applied the new CRDs here and the updated operator?
> > 
> > 
> > I deleted the CRDs and re-created them with the helm chart. Maybe I'm not updating the operator correctly? How would I update that?
> 
> There's a thread in slack where folks talk about that: https://konpytika.slack.com/archives/C0362VBRM24/p1702911625342399
> 
> TLDR is that the helm client doesn't do it for you, but tools like ArgoCD/Flux will do it for you.
> 
> https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

I manually deleted the CRDs, and confirmed they are updated after re-installing the nifikop helm chart. But still, when I deploy a nifi cluster it doesn't seem to add the ldap settings. Seems like it must be something else then.

2024-03-05 14:27 UTC, juldrixx commented
> > > > > For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container. Am I missing something? For example:
> > > > > ```
> > > > > ldapConfiguration
> > > > >   enabled: true
> > > > >   tlsTruststore:  /some/path
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Then if I exec into the container, and cat conf/login-identity-providers.xml , The value for that line item is empty.
> > > > 
> > > > 
> > > > Just double checking you've applied the new CRDs here and the updated operator?
> > > 
> > > 
> > > I deleted the CRDs and re-created them with the helm chart. Maybe I'm not updating the operator correctly? How would I update that?
> > 
> > 
> > There's a thread in slack where folks talk about that: https://konpytika.slack.com/archives/C0362VBRM24/p1702911625342399
> > TLDR is that the helm client doesn't do it for you, but tools like ArgoCD/Flux will do it for you.
> > https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
> 
> I manually deleted the CRDs, and confirmed they are updated after re-installing the nifikop helm chart. But still, when I deploy a nifi cluster it doesn't seem to add the ldap settings. Seems like it must be something else then.

Did you build an image of the operator with your change? Or are you using the `1.7.0`? Or are you running the code locally?

2024-03-05 14:43 UTC, wrender commented
> > > > > > For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container. Am I missing something? For example:
> > > > > > ```
> > > > > > ldapConfiguration
> > > > > >   enabled: true
> > > > > >   tlsTruststore:  /some/path
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Then if I exec into the container, and cat conf/login-identity-providers.xml , The value for that line item is empty.
> > > > > 
> > > > > 
> > > > > Just double checking you've applied the new CRDs here and the updated operator?
> > > > 
> > > > 
> > > > I deleted the CRDs and re-created them with the helm chart. Maybe I'm not updating the operator correctly? How would I update that?
> > > 
> > > 
> > > There's a thread in slack where folks talk about that: https://konpytika.slack.com/archives/C0362VBRM24/p1702911625342399
> > > TLDR is that the helm client doesn't do it for you, but tools like ArgoCD/Flux will do it for you.
> > > https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
> > 
> > 
> > I manually deleted the CRDs, and confirmed they are updated after re-installing the nifikop helm chart. But still, when I deploy a nifi cluster it doesn't seem to add the ldap settings. Seems like it must be something else then.
> 
> Did you build an image of the operator with your change? Or are you using the `1.7.0`? Or are you running the code locally?

Running the code locally. I git cloned my fork, that has the login providers changes for ldap, and then do a helm install of nifikop from that local folder.

2024-03-05 15:08 UTC, juldrixx commented
> > > > > > > For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container. Am I missing something? For example:
> > > > > > > ```
> > > > > > > ldapConfiguration
> > > > > > >   enabled: true
> > > > > > >   tlsTruststore:  /some/path
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > Then if I exec into the container, and cat conf/login-identity-providers.xml , The value for that line item is empty.
> > > > > > 
> > > > > > 
> > > > > > Just double checking you've applied the new CRDs here and the updated operator?
> > > > > 
> > > > > 
> > > > > I deleted the CRDs and re-created them with the helm chart. Maybe I'm not updating the operator correctly? How would I update that?
> > > > 
> > > > 
> > > > There's a thread in slack where folks talk about that: https://konpytika.slack.com/archives/C0362VBRM24/p1702911625342399
> > > > TLDR is that the helm client doesn't do it for you, but tools like ArgoCD/Flux will do it for you.
> > > > https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
> > > 
> > > 
> > > I manually deleted the CRDs, and confirmed they are updated after re-installing the nifikop helm chart. But still, when I deploy a nifi cluster it doesn't seem to add the ldap settings. Seems like it must be something else then.
> > 
> > 
> > Did you build an image of the operator with your change? Or are you using the `1.7.0`? Or are you running the code locally?
> 
> Running the code locally. I git cloned my fork, that has the login providers changes for ldap, and then do a helm install of nifikop from that local folder.

If you didn't build an image of your code  to use in your deployment, it won't work. It will just deploy the latest release of the operator. If you want to run the code locally, you need to use a tool like [telepresence](https://www.telepresence.io/).

2024-03-05 15:49 UTC, juldrixx commented
> > > > > > > > > For some reason when I define these new settings in a cluster crd yaml file, and then deploy a cluster they don't take affect in the container. Am I missing something? For example:
> > > > > > > > > ```
> > > > > > > > > ldapConfiguration
> > > > > > > > >   enabled: true
> > > > > > > > >   tlsTruststore:  /some/path
> > > > > > > > > ```
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > >     
> > > > > > > > >       
> > > > > > > > >     
> > > > > > > > > 
> > > > > > > > >       
> > > > > > > > >     
> > > > > > > > > 
> > > > > > > > >     
> > > > > > > > >   
> > > > > > > > > Then if I exec into the container, and cat conf/login-identity-providers.xml , The value for that line item is empty.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Just double checking you've applied the new CRDs here and the updated operator?
> > > > > > > 
> > > > > > > 
> > > > > > > I deleted the CRDs and re-created them with the helm chart. Maybe I'm not updating the operator correctly? How would I update that?
> > > > > > 
> > > > > > 
> > > > > > There's a thread in slack where folks talk about that: https://konpytika.slack.com/archives/C0362VBRM24/p1702911625342399
> > > > > > TLDR is that the helm client doesn't do it for you, but tools like ArgoCD/Flux will do it for you.
> > > > > > https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
> > > > > 
> > > > > 
> > > > > I manually deleted the CRDs, and confirmed they are updated after re-installing the nifikop helm chart. But still, when I deploy a nifi cluster it doesn't seem to add the ldap settings. Seems like it must be something else then.
> > > > 
> > > > 
> > > > Did you build an image of the operator with your change? Or are you using the `1.7.0`? Or are you running the code locally?
> > > 
> > > 
> > > Running the code locally. I git cloned my fork, that has the login providers changes for ldap, and then do a helm install of nifikop from that local folder.
> > 
> > 
> > If you didn't build an image of your code to use in your deployment, it won't work. It will just deploy the latest release of the operator. If you want to run the code locally, you need to use a tool like [telepresence](https://www.telepresence.io/).
> 
> Ok. Thanks for the information @juldrixx . I'm new to operators in Kubernetes so I will have to spend some time learning this. Is there any documentation on how I would go about the building of a custom image to test with the deployment? I don't know I want to introduce yet another tool like telepresence.

You can find it [here](https://konpyutaika.github.io/nifikop/docs/6_contributing/1_developer_guide) but it doesn't mention telepresence.

2024-03-08 15:48 UTC, mh013370 approved these changes

2024-03-08 15:48 UTC, mh013370 commented
LGTM

2024-03-08 16:06 UTC, juldrixx approved these changes

2024-03-08 16:17 UTC, merged