Feature/nifinodegroupenabling
konpyutaika/nifikop pull request #439
Opened 2024-07-05 07:26 UTC by aswathinj-pai

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?

The current helm chart doesn't handle the replicas attribute in the nifinodegroupautoscaler template in nifi-cluster helm chart. Consequently, it defaults to 0, disabling the HPA created alongside it and preventing autoscaling. Therefore, to enable this feature, we need to manage the replicas attribute in the nifi-node-group-autoscaler.yaml template.

### Checklist

- [x] Implementation tested
- [ ] User guide and development docs updated (if needed)
- [ ] Append changelog with changes

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2024-09-05 08:35 UTC, mh013370 approved these changes

2024-09-06 07:50 UTC, juldrixx requested changes

2024-09-06 07:50 UTC, juldrixx commented on CHANGELOG.md
> +- [PR #439](https://github.com/konpyutaika/nifikop/pull/439) - **[Operator]** Handling the replicas attribute in the nifinodegroupautoscaler template in nifi-cluster helm chart.
```suggestion

- [PR #439](https://github.com/konpyutaika/nifikop/pull/439) - **[Operator]** Handling the replicas attribute in the nifinodegroupautoscaler template in nifi-cluster helm chart.

```

2024-09-06 08:00 UTC, juldrixx commented
And can you fix the conflicts?

2024-09-06 10:50 UTC, aswathinj-pai commented
@juldrixx conflict resolved.

2024-09-06 11:20 UTC, juldrixx requested changes

2024-09-06 11:55 UTC, juldrixx approved these changes

2024-09-06 11:55 UTC, merged