fix(helm): add inheritedParameterContexts support to NiFi ParameterCo…
konpyutaika/nifikop pull request #475
Opened 2024-11-03 19:45 UTC by Roger1uphealth

…ntext template

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets |partially #165
| License         | Apache 2.0

### What's in this PR?

This PR fixes an issue where `inheritedParameterContexts` specified in values.yaml for NifiParameterContext resources were not rendered in the Helm template. 

The fix adds conditional rendering of inheritedParameterContexts in the Helm template, aligning it with the CRD schema and ensuring that any defined inherited contexts are correctly included in the generated YAML.

### Why?

Inherited parameter contexts were not being deployed as expected due to the missing field in the Helm template.

### Checklist

- [ ] Implementation tested
- [ ] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [ ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)
- [ ] Append changelog with changes

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2024-11-03 23:01 UTC, juldrixx requested changes

2024-11-03 23:01 UTC, juldrixx commented on CHANGELOG.md
> + - [PR #476](https://github.com/konpyutaika/nifikop/pull/475) - **[Helm chart]** Added option in nifi-parameter-context helm chart to support setting `inheritedParameterContexts`.
```suggestion
### Fixed Bugs

 - [PR #476](https://github.com/konpyutaika/nifikop/pull/475) - **[Helm chart]** Added option in nifi-parameter-context helm chart to support setting `inheritedParameterContexts`.
```

2024-11-03 23:03 UTC, juldrixx commented
And can you regenerte the Helm doc using [helm docs](https://github.com/norwoodj/helm-docs)?

```shell
cd helm/nifi-cluster
helm-docs
```

2024-11-03 23:11 UTC, juldrixx requested changes
Can you move it to `### Added` instead of `### Fixed Bugs`.

And put a capital letter on `Chart` in `[Helm chart]`.

2024-11-03 23:17 UTC, juldrixx requested changes
Can you add it in the `Unreleased` section at the beginning of the file?

2024-11-03 23:19 UTC, juldrixx requested changes
Can you add the field in `values.yaml` too with a comment that will be part of the generated documentation like it's done for `secretRefs` and `parameters`.

2024-11-03 23:45 UTC, Roger1uphealth commented
@juldrixx thanks for quick review and patience.  I think it's in a spot where it can be reviewed again when you have time.

2024-11-04 07:55 UTC, juldrixx commented
Thanks for your contribution🙌.

2024-11-04 07:55 UTC, merged